# .github/workflows/ci-cd.yml

name: TensorFlow CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on push to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Specify the version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest --maxfail=1 --disable-warnings -q

    - name: Train model (optional step)
      run: |
        python src/train.py

    - name: Upload model artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: model-artifact
        path: model.h5
